### ISSUE TITLE
Search transition and color 

### ISSUE THREAD

**Issue by successbyte** [ehsanullahhaidary/dribble-clone#1]
when hovering the mouse on search icon in the header the icons does not have transition and change color

![Screenshot 2024-09-06 171933](https://github.com/user-attachments/assets/38e86d03-1a01-4f06-a67c-a961458770de)

**Comment by Rahul-2006** [comment]
Hi @ehsanullahhaidary 
I am a beginner and i want to contribute in this since this is a easy one and helps me build my open source journey
So please assign this to me

**Comment by successbyte** [comment]
Hi @Rahul-2006 I assigned it to you, You may create a PR

**Comment by Rahul-2006** [comment]
can you please help me in setting up the project and tell me how to test it?

**Comment by successbyte** [comment]
Hi @Rahul-2006  I updated the Readme.md check it 
it guides you how to setup the app
if couldn't run the app comment here please

**Comment by Rahul-2006** [comment]
Hi @ehsanullahhaidary  I sent you a pull request 
please check it and tell me if you need any changes

**Comment by Rahul-2006** [comment]
is everything ok @ehsanullahhaidary ?

**Comment by successbyte** [comment]
Hi @Rahul-2006 
yep everything is great
please just include the header.scss or any .scss files that you may change and so not push other files.
thanks

**Comment by successbyte** [comment]
exclude all other changes please

**Comment by successbyte** [comment]
Hi @Rahul-2006 
could you please give the repo a star.

**Comment by Rahul-2006** [comment]
Can you please suggest me repos where i can go and contribute 
I am trying to contribute but i cant find issues related to my stacks (html, css and basic js) 
.....

**Comment by successbyte** [comment]
Hi @Rahul-2006 search in bellow link
https://github.com/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by successbyte** [comment]
and also go to https://opensauced.pizza/
