### ISSUE TITLE
Header Sign in button color transition

### ISSUE THREAD

**Issue by successbyte** [ehsanullahhaidary/dribble-clone#10]
# New Issue

The sign in button in header does not have a color transition

## Actual behavior

![Screenshot 2024-09-10 220450](https://github.com/user-attachments/assets/a555e70d-a33d-4008-bbcc-c96b520e6065)

## Expected behavior

When hover the mouse over the button it should change the color in 200ms with an ease-in-out transition

**Comment by successbyte** [comment]
if you have any question regarding the issue or more info on Open Source ask here or reach out to me
https://x.com/Ehsan_Haidary

**Comment by Rahul-2006** [comment]
Hi @ehsanullahhaidary  can you assign this to me 
this time i would give the same transition as you mentioned

**Comment by successbyte** [comment]
Hi @Rahul-2006 I assigned the issue to you
the last time you changed the main style.css file please read the Readme.md of repo.
I changed the project structure a little bit.
work in SCSS files.

**Comment by successbyte** [comment]
Hi @Rahul-2006 
could you please give the repo a star.
