### ISSUE TITLE
The eye icon in cards right bottom hover

### ISSUE THREAD

**Issue by successbyte** [ehsanullahhaidary/dribble-clone#13]
# New Issue
The cards at middle section has an eye icon at the right bottom when hover the mouse on the eye the color of icon changes but the cursor does not changes to pointer, I want when the user hover mouse on it the mouse cursor to be pointer

Actual behavior
when hover mouse on the Icon the mouse cursor does not change

![Screenshot 2024-09-10 220916](https://github.com/user-attachments/assets/9ea30bc5-bc3b-4f8b-b8f5-c465d24228c9)

Expected behavior
I want the mouse to change to `cursor: pointer`

**Comment by successbyte** [comment]
if you have any question regarding the issue or more info on Open Source ask here or reach out to me
https://x.com/Ehsan_Haidary

**Comment by TanviiSaraf** [comment]
@successbyte Hii, can you assign this issue to me?

**Comment by successbyte** [comment]
Hi @TanviiSaraf assigned you
please give the repo a star that the other also could find it easily and contribute
thanks Tanvi
