### ISSUE TITLE
Search transition and color

### ISSUE THREAD

**Issue by successbyte** [ehsanullahhaidary/dribble-clone#22]
when hovering the mouse on search icon in the header the icons blinks (it  has an animation that changes it's opacity)
I want that to be disabled
![Screenshot 2024-09-06 171933](https://github.com/user-attachments/assets/38e86d03-1a01-4f06-a67c-a961458770de)

**Comment by MiteshDalvi** [comment]
Can you assign me this task?

**Comment by successbyte** [comment]
assigned you 
you may create PR
