### ISSUE TITLE
Header Dribbble icon Transition

### ISSUE THREAD

**Issue by raziq-quraishi** [ehsanullahhaidary/dribble-clone#3]
in the footer  Dribbble logo has a nice transition but in the header Dribbble logo does not have a transition. I want to set a nice transition to the header logo.

**Comment by raziq-quraishi** [comment]
please assign this task to me to add a transition to the header logo.

**Comment by successbyte** [comment]
Hi @raziq-quraishi I assigned it to you 
you may do your changes and create a PR

**Comment by successbyte** [comment]
Hi @raziq-quraishi  
could you please give the repo a star.
