### ISSUE TITLE
White box around search icon in header

### ISSUE THREAD

**Issue by successbyte** [ehsanullahhaidary/dribble-clone#6]
# header search Icon white box
In header the search icon when hover has a white box around it inside the shadow 

# Expected behavior
the rotate should be deleted and also the shadow it just need a transition.

# screenshot of problem
![Capture](https://github.com/user-attachments/assets/ec5b6fdd-4bbf-44b7-ae64-b3583dbb9796)

**Comment by zabihullahYaqubi585352** [comment]
Can I please be assigned to this issue ?

**Comment by Punith1117** [comment]
may I know the issue in detail?
The rotate-animation and shadow(glow) should be removed and white box should remain as it is. The svg when hovered should just get its fill-color changed and nothing else?

**Comment by successbyte** [comment]
Hi @Punith1117 the transition with the color change should be still there and all other like Rotate, white box should be removed

**Comment by successbyte** [comment]
I assigned this issue to @zabihullahYaqubi585352 as he commented before you and if you want to contribute and if its your first time then welcome

**Comment by successbyte** [comment]
@Punith1117 you can create an issue or a feature ex: change a button color or add another feature you are welcomed

**Comment by successbyte** [comment]
@zabihullahYaqubi585352 you may run the app as told in Readme.md and create a PR

**Comment by zabihullahYaqubi585352** [comment]
thanks

**Comment by zabihullahYaqubi585352** [comment]
Hi

**Comment by zabihullahYaqubi585352** [comment]
to run the node-sass: node-sass scss/main.scss css/style.css -w  it doesn't any reaction  how to run  sass  file .

**Comment by zabihullahYaqubi585352** [comment]
I also installed node-sass and after that , or this command run with npm or ant others

**Comment by Rahul-2006** [comment]
@ehsanullahhaidary 
I would have done it myself if you have said it before 
I thought making it transition could make the website more attractive 
Anyways thank you for giving me an assign before...

**Comment by successbyte** [comment]
Hi @zabihullahYaqubi585352 
after you cloned the repo to your machine do bellow steps:
- npm install -g node-sass
- node-sass scss/main.scss css/style.css -w
keep the above terminal be running (do not stop the above command terminal)
as long as you run the above command the SCSS files are ready to be changed and it will automatically change the project styled

**Comment by successbyte** [comment]
Hi @Rahul-2006,
thanks for the work 
understand that open-source is solving the problem step by step not in one step
and also I created this repo for people like you that wanted to start their first contribution 
tell all your friends if they are interested 
you can easily create small issues ex: change a button color, and tell me to assign it to you and work on it

**Comment by successbyte** [comment]
if you have any question regarding the issue or more info on Open Source ask here or reach out to me
https://x.com/Ehsan_Haidary

**Comment by successbyte** [comment]
Hi @zabihullahYaqubi585352  
could you please give the repo a star.

**Comment by zabihullahYaqubi585352** [comment]
Hi @successbyte 
Of course  yes how can I do this, like this ⭐️ ⭐️

**Comment by successbyte** [comment]
Hi @zabihullahYaqubi585352  
please go to https://github.com/successbyte/dribble-clone link and 
at the right top corner click star

![image](https://github.com/user-attachments/assets/b38c7a4c-5bde-4800-bb38-4fe8da208320)
