### ISSUE TITLE
Selected text color

### ISSUE THREAD

**Issue by successbyte** [ehsanullahhaidary/dribble-clone#9]
# New Issue
The selected text color is somehow pink and I want it to be changes to a blue color with a little opacity 
ex: when selecting a the text color should be `#e0e0e0` and the background color should be `#2782b382`

## Actual behavior

![Screenshot 2024-09-10 220412](https://github.com/user-attachments/assets/c47ec3ee-7e7b-4709-aa4c-a978f8d0afeb)

## Expected behavior

![Screenshot 2024-09-10 222030](https://github.com/user-attachments/assets/a39eda33-5afb-4062-a286-da11aabd6884)

**Comment by successbyte** [comment]
if you have any question regarding the issue or more info on Open Source ask here or reach out to me
https://x.com/Ehsan_Haidary

**Comment by Punith1117** [comment]
can I please get assigned to this issue

**Comment by Pranathi1314** [comment]
hi @successbyte please assign this issue to me. I'm new to open source contributions and would like to work on it.

**Comment by successbyte** [comment]
Hi @Pranathi1314 Done 
You may create a PR
